GET http://localhost:5291
###
GET http://localhost:5291/games
###
GET http://localhost:5291/games/5
###
POST http://localhost:5291/games
Content-Type: application/json

{
  "name": "GTA VI",
  "GenreId": 1 ,
  "Price": 50,
  "releaseDate": "2025-09-17"
}

###
PUT http://localhost:5291/games/5
Content-Type: application/json

{
  "name": "GTA V",
  "GenreId": 1,
  "Price": 50,
  "releaseDate": "2013-09-18"
}

###

DELETE http://localhost:5291/games/4